config/routes.rb
Rails.application.routes.draw do
  get "/", to: "reserve#home"
  get "/reserve/search", to: "reserve#search"
  get "/reserve/staffs", to: "reserve#staff_all"
  get "/reserve/staff/:staff_id", to: "reserve#schedule"
  get "/reserve/staff/:staff_id/confirm", to: "reserve#confirm"
  post "/reserve/staff/:staff_id", to: "reserve#create_reservation"
  post "/staffs/import", to: "staffs#import"
end

app/controllers/reserve_controller.rb
class ReserveController < ApplicationController
  def home

  end

  def schedule
    @staff = Staff.find(params[:staff_id])
    @today = Time.zone.today # + 10.hours # 10:00 から表示
    @schedules = @staff.schedules.where('date >= ?', @today)
    @time_slots = @schedules.map { |s| s.time_slots.order(:start_time) }.flatten
  end

  def search
    @start_time_from = params[:start_time_from]

    now = Time.zone.now
    search_time_from_now = Time.new(now.year, now.month, now.day, now.hour, (now.min / 10) * 10, 0, '+09:00') + 30.minutes

    search_start_time = if @start_time_from.present?
                          h, m = @start_time_from.split(':')
                          Time.new(now.year, now.month, now.day, h, m, 0, '+09:00')
                        else
                          @start_time_from = search_time_from_now.strftime('%H:%M')
                          search_time_from_now
                        end

    @select_array = []
    temp_time = search_time_from_now
    tomorrow = Time.zone.today + 24.hours
    while temp_time < tomorrow
      @select_array << temp_time.strftime('%H:%M')
      temp_time += 10.minutes # 10分刻み
    end

    # 希望した開始日時より、スタートが同じか早いタイムスロットを取得
    # 希望した終了日時より、エンドがちょうどか遅いタイムスロットを取得
    # @shop.search
    @time_slots = Schedule.search(search_start_time, nil, 90)

    @search_start_time = search_start_time
  end

  def staff_all
    @start_date = Time.zone.today
    @end_date = @start_date + 1.days
    @schedules = Schedule.where('date >= ? AND date <= ?', @start_date, @end_date).includes(:staff).order(:start_time)
    @staffs = @schedules.map(&:staff).uniq
  end

  def confirm
    @staff = Staff.find(params[:staff_id])
  end

  def create_reservation
    @staff = Staff.find(params[:staff_id])
    @duration = 90.minutes
    @schedule = @staff.schedules.find_by!(date: Time.zone.today)
    @schedule.create_reservation(Time.zone.parse(params[:start_time]), @duration)
    redirect_to '/'
  end
end

app/helpers/reserve_helper.rb
module ReserveHelper
  def confirm_path(staff_id, start_time)
    "/reserve/staff/#{staff_id}/confirm?start_time=#{start_time.strftime('%Y-%m-%d %H:%M')}"
  end
end

app/views/reserve/confirm.html.erb
<div class="row justify-content-center mt-3">
  <div class="col-md-6">
    <h1>予約確認</h1>
    <table class="table">
      <tr>
        <th>スタッフ名</th>
        <td><%= @staff.name %></td>
      </tr>
      <tr>
        <th>コース名</th>
        <td><%= "天国コース" %></td>
      </tr>
      <tr>
        <th>予約日時</th>
        <td><%= params[:start_time] %></td>
      </tr>
    </table>

    <%= form_with(url: "/reserve/staff/#{@staff.id}", method: :post, local: true) do |form| %>
      <%= form.hidden_field :staff_id, value: params[:staff_id] %>
      <%= form.hidden_field :start_time, value: params[:start_time] %>

      <div class="form-group mb-3 ">
        <%= form.label :name, '名前', class: 'col-sm-2 col-form-label' %>
        <div class="col-sm-10">
          <%= form.text_field :name, class: 'form-control', required: false %>
        </div>
      </div>

      <div class="form-group mb-3">
        <%= form.label :phone_number, '電話番号', class: 'col-sm-2 col-form-label' %>
        <div class="col-sm-10">
          <%= form.text_field :phone_number, class: 'form-control', required: false %>
        </div>
      </div>

      <div class="form-group mb-3">
        <%= form.label :email, 'メールアドレス', class: 'col-sm-3 col-form-label' %>
        <div class="">
          <%= form.email_field :email, class: 'form-control', required: false %>
        </div>
      </div>

      <div class="form-group row">
        <div class="col-sm">
          <%= form.submit '予約する', class: 'btn btn-primary' %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/reserve/home.html.erb
<div class="row justify-content-center mt-3">
  <div class="col-md-12 text-center">
    <h1>ようこそ</h1>

    <%= link_to "セラピストから今すぐ簡単予約", '/reserve/staffs', class: "btn btn-primary btn-lg" %>

    <%= link_to "カレンダーから今すぐ簡単予約", '/reserve/search', class: "btn btn-primary btn-lg" %>
  </div>
</div>

app/views/reserve/schedule.html.erb
<% start_time = @today + 10.hours %>
<% end_time = start_time + 14.hours %>
<% current_time = start_time %>
<% wdays = ["日", "月", "火", "水", "木", "金", "土"] %>

<h1><%= @staff.name %> さんの空き情報 <%= start_time %>から</h1>
<img src="<%= @staff.image_url %>" alt="<%= @staff.name %>">
<table class="table-style">
  <tr>
    <th></th>
    <% 7.times do |n| %>
      <% temp_time = current_time + n.days %>
      <th><%= temp_time.strftime("%d") %><br><%= wdays[temp_time.wday] %></th>
    <% end %>
  </tr>

  <!--  10:00から10分刻みでの時間を表示-->
  <% while current_time <= end_time do %>
    <tr>
      <td>
        <%= current_time.strftime("%H:%M") %>
      </td>
      <% 7.times do |n| %>
        <% temp_time = current_time + n.days %>
        <% if @schedules.any? { |s| s.start_time <= temp_time && temp_time < s.end_time } %>
          <% if @time_slots.any? { |ts| ts.can_reserve?(temp_time) } %>
            <td class="available-slot">
              <%= link_to '◯', confirm_path(@staff.id, temp_time) %>
            </td>
          <% else %>
            <td class="unavailable-slot">✖️</td>
          <% end %>
        <% else %>
          <td class="unavailable-slot">-</td>
        <% end %>
      <% end %>
    </tr>
    <% current_time += 10.minutes %>
  <% end %>
</table>

app/views/reserve/search.html.erb
<h1>予約検索</h1>
<%= form_with(url: reserve_search_path, method: :get, local: true) do |form| %>
  <div class="form-group row mb-3">
    <%= form.label :start_time_from, "開始時間 (から)", class: 'col-sm-2 col-form-label' %>
    <div class="col-sm-10">
      <%= form.select :start_time_from, @select_array, { selected: @start_time_from }, { class: 'form-control', required: true } %>
    </div>
  </div>

  <div class="form-group row">
    <div class="col-sm-10 offset-sm-2">
      <%= form.submit '検索', class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>

<hr>

<h2>検索結果</h2>

<p><%= @search_start_time.strftime("%m/%d %H:%M") %>以降の予定を検索しました</p>

<% @time_slots.each do |_, v| %>
  <% staff = v.first.schedule.staff %>
  <div class="time_slot">
    <h3><%= link_to staff.name, "/reserve/staff/#{staff.id}" %></h3>
    <img src="<%= staff.image_url %>" alt="">
    <ul>
      <% v.each do |time_slot| %>
        <li><%= link_to "#{time_slot.actual_start_time(@search_start_time).strftime("%m/%d %H:%M")} スタートで予約", confirm_path(staff.id, time_slot.actual_start_time(@search_start_time)), class: "btn btn-primary" %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/reserve/staff_all.html.erb
<h1>セラピストを選択</h1>
<p><%= @start_date %> に出勤予定</p>
<table class="table table-striped">
  <tbody>
  <% @schedules.each do |schedule| %>
    <% staff = schedule.staff %>
    <tr>
      <td><%= staff.staff_id %></td>
      <td>
        <%= image_tag staff.image_url, class: 'img-thumbnail', width: '70' %>
      </td>
      <td><%= staff.name %></td>
      <td><%= "#{schedule.start_time.strftime('%H:%M')} - #{schedule.end_time.strftime('%H:%M')}" %></td>
      <td><%= link_to '選択する', "/reserve/staff/#{staff.id}", class: "btn btn-primary btn-lg" %></td>
    </tr>
  <% end %>
  </tbody>
</table>